### ISSUE TITLE
About the 0.1.6 release

### ISSUE THREAD

**Issue by iMichka** [smmr-software/mabel#13]
Hi. Homebrew maintainer here. We noticed you pushed a 0.1.5 and 0.1.6 tag. The 0.1.6 tag has not been marked as the latest release, which is still 0.1.4. Is this on purpose?

https://github.com/Homebrew/homebrew-core/pull/108082 for reference

**Comment by FIGBERT** [comment]
We have some internal debate at SMMR Software about using GitHub Releases as opposed to Git Tags, and the former always lag behind the latter (though typically that's by minutes rather than hours).

I will go create the releases now, but also state that tags should be considered the canonical version.

Thank you for reaching out!

**Comment by iMichka** [comment]
Thanks.

Some packages prefer to use tags only, some use tags + releases. But it's quite rare that only the first tags are marked as a release and then it suddenly stops: we prefer consistency, and always double check with upstream.

We will follow the tags then. Thanks!
